### PR TITLE
Oopsassignment/4

### PR DESCRIPTION
**Pull request by Ranapriyanshi**
🔅Submission for Milestone 4  - **BuzzOn**

🌀**OOPS concepts  -**    

- [✔️] **Inheritance**  
 
 
- [✔️] **Abstract Class**     
    
Here is the loom video explaining the demonstration of concepts into BuzzOn. -
✨[**`Inheritance and Abstract class`**](https://www.loom.com/share/52c76b7c6b2442dbbd813b14d67ac887?sid=839d9107-2521-44c5-964a-0041dfd2c7bd)
 

🕵️**Project Demonstration** - [Demo Video](https://www.loom.com/share/e28ccaa3fe9c4c0f815a60e0bf4880c9?sid=ab537c7a-1273-4070-9171-b41244d18b62)
              _Description -_  This is a detailed explanation video containing a live demonstration of the project and a brief account of the tech stack.

### CODE REVIEW

**Comment by Ranapriyanshi** [comment]
Here is the loom video explaining the demonstration of concepts into BuzzOn. -  
✨Inheritance and Abstract class
[](https://www.loom.com/share/fdf74694ed9f415ab092ce571a355410?sid=94549acb-1af8-40c8-99b5-5104b6b65471)

**Comment by th3c0d3br34ker** [comment]
#3 merged without approval.

**Comment by Ranapriyanshi** [comment]
Actually, It got merged automatically as I merged the one for DBMS as #3 was based out of that.

**Comment by th3c0d3br34ker** [comment]
please create a new PR and re-submit

**Comment by Ranapriyanshi** [comment]
Hey, how can I do that, when I have my changes already merged??

**Comment by Ranapriyanshi** [comment]
Are there any issues with the merged PR??

**Comment by th3c0d3br34ker** [comment]
thanks @Ranapriyanshi for your submission. please make sure you raise proper PR for each concept.

considering this PR for `Inheritance` and `Abstract Class`.

**Review by th3c0d3br34ker — APPROVED** [review]

**Pull request merged**
