### PR TITLE
Dbmsassignment/3

### PR DESCRIPTION
**Pull request by Ranapriyanshi**
🔅Submission for Milestone 3  - **BuzzOn**

🌀**DBMS concepts  -**  
  

- [✔️] **Role-Based Access Control- creating roles & privileges**  
                      Here is the loom video recording explaining the implementation in the project.✨[Role-Based Access Control- creating roles & privileges](https://www.loom.com/share/fdf74694ed9f415ab092ce571a355410?sid=5c490dde-209e-4c10-b697-0e2a84151421)  
 
- [✔️] **Advanced SQL Queries - Joins, subqueries**   
                      Here is the loom video recording explaining implementation in the project.✨[Advanced SQL Queries - Joins, subqueries](https://www.loom.com/share/6450a3bf97e44746a746fc6b436a4a3b?sid=51951456-b4f9-4ef7-882e-d07f5ecca3c0)  

🕵️**Project Demonstration** - [Demo Video](https://www.loom.com/share/6450a3bf97e44746a746fc6b436a4a3b?sid=9a729c75-e94a-41e8-aede-eed18da1e29b)
              _Description -_  This is a detailed explanation video containing a live demonstration of the project and a brief account of the tech stack.  
  

Here are some of the relevant **Screenshots**-   
✍️_**Role-Based Access Control- creating roles & privileges-**_
image    

image
  
✍️_**Advanced SQL Queries - Joins, subqueries**-_  

image
  
image

### CODE REVIEW

**Comment by th3c0d3br34ker** [comment]
hey @Ranapriyanshi please schedule a viva [for OOP and DBMS]. the link for the same is available in the wiki.

**Comment by Ranapriyanshi** [comment]
Here is the explanation video link-
https://www.loom.com/share/6450a3bf97e44746a746fc6b436a4a3b?sid=9a729c75-e94a-41e8-aede-eed18da1e29b

**Comment by Ranapriyanshi** [comment]
Hey, I have updated the links.

**Comment by th3c0d3br34ker** [comment]
Thanks @Ranapriyanshi for your submission.  

Please go ahead and merge this PR.

**Review by th3c0d3br34ker — APPROVED** [review]

**Pull request merged**
